# Generated by Django 4.2 on 2023-05-23 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('address', models.TextField(blank=True, max_length=30, null=True)),
                ('phone', models.CharField(max_length=15)),
            ],
        ),
    ]
