# Generated by Django 4.2 on 2023-05-26 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newappdbms', '0004_paymentdetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=100, unique=True)),
                ('students', models.ManyToManyField(blank=True, null=True, to='newappdbms.student')),
            ],
        ),
    ]
