# Generated by Django 4.2 on 2023-05-29 05:42

from django.db import migrations, models
import newapp1.models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='mobile_no',
            field=models.CharField(max_length=15, validators=[newapp1.models.my_mobile_validetor]),
        ),
    ]
