# Generated by Django 4.2 on 2023-06-01 10:46

from django.db import migrations, models
import newapp1.models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp1', '0002_alter_customer_mobile_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='mobile_no',
            field=models.CharField(max_length=15, validators=[newapp1.models.my_mobile_validetor, newapp1.models.my_mobile_validetor2]),
        ),
    ]
