# Generated by Django 4.2 on 2023-06-09 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('Emp_id', models.AutoField(primary_key=True, serialize=False)),
                ('Emp_email', models.CharField(max_length=200)),
                ('Emp_password', models.CharField(max_length=40)),
                ('Emp_name', models.CharField(max_length=200)),
                ('Emp_mobno', models.CharField(max_length=10)),
                ('Emp_age', models.IntegerField(max_length=2)),
                ('Emp_depart', models.CharField(max_length=200)),
                ('Emp_role', models.CharField(max_length=200)),
                ('Emp_expinyears', models.IntegerField(max_length=2)),
            ],
        ),
    ]
