# Generated by Django 4.2 on 2023-06-07 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userMgt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='photo',
            field=models.ImageField(null=True, upload_to='cus_pic'),
        ),
    ]
